Token: "OTIyNzcxMTM3MzI5NDk2MDY0.GryXxR.u5e45K33s7AYijdYFaNJzqKH38znvJCaniqAac"

Lavalink:
  Name: "ARINO Music"
  Hostname: "us.sanode.xyz"
  Port: 25568
  Password: "discord.gg/W2GheK3F9m"
  Secured: false
  SearchType: youTube

# Token: "OTIyNzcxMTM3MzI5NDk2MDY0.GryXxR.u5e45K33s7AYijdYFaNJzqKH38znvJCaniqAac"

# Lavalink:
#   Name: "Mi serverr"
#   Hostname: "192.168.1.39"
#   Port: 2333
#   Password: "youshallnotpass"
#   Secured: false
#   SearchType: soundCloud