Token: "OTIyNzcxMTM3MzI5NDk2MDY0.GryXxR.u5e45K33s7AYijdYFaNJzqKH38znvJCaniqAac"

Lavalink:
  Name: "test"
  Hostname: "lava-v4.ajieblogs.eu.org"
  Port: 80
  Password: "https://dsc.gg/ajidevserver"
  Secured: false

# Token: "OTIyNzcxMTM3MzI5NDk2MDY0.GryXxR.u5e45K33s7AYijdYFaNJzqKH38znvJCaniqAac"

# Lavalink:
#   Name: "test"
#   Hostname: "192.168.1.39"
#   Port: 8080
#   Password: "youshallnotpass"
#   Secured: false